### ISSUE TITLE
Advanced permissions system

### ISSUE THREAD

**Issue by xenforq** [newgentdigital/kloey#5]
### Is your feature request related to a problem?
It's always nice to have multiple options when configuring something, therefore adding a more advanced and customizable permissions system to Kloey would be highly appreciated. Allowing more opportunities with it's installments.

### Describe the solution you'd like
- Only allow a specific role per each command
-- Preferably should be based on the role ID
- Toggleable option to only allow the set "mention" role for a brand to access the ticket

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by bleachyblue** [comment]
I have began development on this feature and it should be finished some time tomorrow

**Comment by bleachyblue** [comment]
The features have been added in the latest commit. Please check the permissions.json file to set permissions for each role id. Ensure the permissions file is moved over to the VPS otherwise the bot will error on start and will remain in a disabled state.

You can change the toggleable option if brand roles can access their specific tickets in the config file. (true/false)
